name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - id: version
        name: Get Version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: $GITHUB_REPOSITORY_OWNER
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Client Image
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          push: true
          file: client/Dockerfile
          tags: |
            amruthpillai/reactive-resume:client-latest
            amruthpillai/reactive-resume:client-${{ steps.version.outputs.tag }}
            ghcr.io/amruthpillai/reactive-resume:client-latest
            ghcr.io/amruthpillai/reactive-resume:client-${{ steps.version.outputs.tag }}

  server:
    name: Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - id: version
        name: Get Version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: $GITHUB_REPOSITORY_OWNER
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Server Image
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          push: true
          file: server/Dockerfile
          tags: |
            amruthpillai/reactive-resume:server-latest
            amruthpillai/reactive-resume:server-${{ steps.version.outputs.tag }}
            ghcr.io/amruthpillai/reactive-resume:server-latest
            ghcr.io/amruthpillai/reactive-resume:server-${{ steps.version.outputs.tag }}
